"""spot_the_diff -- find the odd emoji in a 4x4 grid.

Each round paints 16 little pixel-art emojis. Fifteen of them are the
same; one is subtly different (mouth flipped, color swapped, mirrored
orientation, missing dot, etc.). Move the highlight with the arrow
keys and press SPACE on the odd one. Three lives, score goes up by 1
per correct pick.

### Controls

    , . ; /   move cursor (left / down / up / right)
    A S W D   alternate movement (gamer scheme)
    SPACE     pick the highlighted cell
    R         restart on the game-over screen
    `         exit back to the launcher

### Why bitmaps instead of real emojis

The DejaVu / Montserrat fonts shipped with this firmware don't have
emoji glyphs — drawing a face from a string would just show a tofu
box. Every "emoji" here is a 10x9 character bitmap rendered at 2x
scale (20x18 px on screen), painted with `fillRect`. Run-length
coalescing in `_draw_bitmap` cuts the per-icon SPI traffic to a few
dozen calls per row, which keeps the 16-cell refresh under a frame.

### Layout (240x135)

    Header:      y=0..19    DARK band, ORANGE hairline at y=20
    Play grid:   y=22..113  4x4 grid of 60x23 cells (contiguous)
    Hint strip:  y=117..134 DARK band, controls hint

Grid: x = col * 60, y = 22 + row * 23, each cell 60 wide x 23 tall.
"""

import random
import time

import M5
import machine
from hardware import MatrixKeyboard


# Palette inlined from ui_theme — matches snake / whack / claude_buddy.
_BLACK = 0x000000
_ORANGE = 0xCC785C
_CREAM = 0xF0EEE6
_DARK = 0x1F1F1F
_GRAY_MID = 0x777777
_RED = 0xE05A4A
_GREEN = 0x55C878

# Extras for the emoji palettes. Picked to read against the black
# play-area background and to keep the "different" variant subtle but
# spottable on the 240x135 LCD.
_YELLOW = 0xF5D86A
_PINK = 0xF08AB0
_BROWN = 0x8B5A2B
_LEAF_G = 0x4FA85C
_WHITE = 0xEEEEEE
_BLUE = 0x3F7BBF
_CYAN = 0x6BC8F0

_LCD = M5.Lcd
_W = 240
_H = 135

_CELL_W = 60
_CELL_H = 23
_COL_X = (0, 60, 120, 180)
_ROW_Y = (22, 45, 68, 91)

# Bitmap size and scale. 10x9 source @ scale 2 = 20x18 on screen,
# centered in the 60x23 cell with a comfortable margin so the cursor
# border doesn't kiss the icon.
_BMP_W = 10
_BMP_H = 9
_SCALE = 2
_ICON_PX_W = _BMP_W * _SCALE
_ICON_PX_H = _BMP_H * _SCALE

_START_LIVES = 3
_FLASH_MS = 220


def _cell_xy(idx):
    return _COL_X[idx % 4], _ROW_Y[idx // 4]


def _cell_center(idx):
    x, y = _cell_xy(idx)
    return x + _CELL_W // 2, y + _CELL_H // 2


def _set_font():
    try:
        _LCD.setFont(_LCD.FONTS.DejaVu9)
    except Exception as e:
        print("spot_diff: setFont fallback:", e)


# === Bitmap renderer =====================================================

def _draw_bitmap(cx, cy, bm, palette):
    """Render a small character bitmap centered at (cx, cy).

    `palette` maps each char in `bm` to an RGB color or to `None`
    (transparent — used for '.' background pixels). Adjacent same-char
    cells in a row are coalesced into one fillRect; with 16 icons at
    81 cells each, naive per-pixel rendering would issue 1300+ SPI
    writes per puzzle and visibly tear during the refresh."""
    ox = cx - _ICON_PX_W // 2
    oy = cy - _ICON_PX_H // 2
    for ry, row in enumerate(bm):
        rx = 0
        L = len(row)
        while rx < L:
            ch = row[rx]
            n = 1
            while rx + n < L and row[rx + n] == ch:
                n += 1
            color = palette.get(ch)
            if color is not None:
                _LCD.fillRect(
                    ox + rx * _SCALE,
                    oy + ry * _SCALE,
                    n * _SCALE,
                    _SCALE,
                    color,
                )
            rx += n


# === Puzzles =============================================================
# Each puzzle is (normal_bitmap, different_bitmap, palette).
# Both bitmaps are 9 rows of 10 chars. '.' is the transparent background.
# Per round we pick one puzzle and an `invert` flag, so half the time
# you're hunting the only frown among smiles and the other half the
# only smile among frowns — keeps the game from feeling one-directional.

_SMILE = (
    [
        "..YYYYYY..",
        ".YYYYYYYY.",
        "YYBYYYYBYY",
        "YYYYYYYYYY",
        "YYYYYYYYYY",
        "YYBYYYYBYY",
        "YYYBBBBYYY",
        ".YYYYYYYY.",
        "..YYYYYY..",
    ],
    [
        "..YYYYYY..",
        ".YYYYYYYY.",
        "YYBYYYYBYY",
        "YYYYYYYYYY",
        "YYYYYYYYYY",
        "YYYBBBBYYY",
        "YYBYYYYBYY",
        ".YYYYYYYY.",
        "..YYYYYY..",
    ],
    {".": None, "Y": _YELLOW, "B": _BLACK},
)

# Heart: same shape, color swapped. Generated by string replace to
# keep the two bitmaps trivially in sync if the silhouette changes.
_HEART_RED = [
    "..........",
    "..RR.RR...",
    ".RRRRRRR..",
    ".RRRRRRR..",
    ".RRRRRRR..",
    "..RRRRR...",
    "...RRR....",
    "....R.....",
    "..........",
]
_HEART_PINK = [row.replace("R", "P") for row in _HEART_RED]
_HEART = (
    _HEART_RED,
    _HEART_PINK,
    {".": None, "R": _RED, "P": _PINK},
)

_APPLE = (
    [
        "..........",
        "....B.....",
        "...GB.....",
        "..GGRRR...",
        ".RRRRRRRR.",
        ".RRRRRRRR.",
        ".RRRRRRRR.",
        "..RRRRRR..",
        "...RRRR...",
    ],
    [
        "..........",
        ".....B....",
        ".....BG...",
        "...RRRGG..",
        ".RRRRRRRR.",
        ".RRRRRRRR.",
        ".RRRRRRRR.",
        "..RRRRRR..",
        "...RRRR...",
    ],
    {".": None, "R": _RED, "G": _LEAF_G, "B": _BROWN},
)

_FISH = (
    [
        "..........",
        ".O..OOOO..",
        "OO.OOOOOO.",
        "OOOOOOOOOO",
        "OOOOOOOOOB",
        "OOOOOOOOOO",
        "OO.OOOOOO.",
        ".O..OOOO..",
        "..........",
    ],
    [
        "..........",
        "..OOOO..O.",
        ".OOOOOO.OO",
        "OOOOOOOOOO",
        "BOOOOOOOOO",
        "OOOOOOOOOO",
        ".OOOOOO.OO",
        "..OOOO..O.",
        "..........",
    ],
    {".": None, "O": _ORANGE, "B": _BLACK},
)

_STAR = (
    [
        "....Y.....",
        "....Y.....",
        "...YYY....",
        "YYYYYYYYY.",
        ".YYYYYYY..",
        "..YYYYY...",
        ".YYY.YYY..",
        ".YY...YY..",
        "..........",
    ],
    [
        "....Y.....",
        "...YYY....",
        "..YYYYY...",
        ".YYYYYYY..",
        "YYYYYYYYY.",
        ".YYYYYYY..",
        "..YYYYY...",
        "...YYY....",
        "....Y.....",
    ],
    {".": None, "Y": _YELLOW},
)

_MUSHROOM = (
    [
        "..........",
        "..RRRRRR..",
        ".RRRRRRRR.",
        "RRWRRRRWRR",
        "RRRRRWRRRR",
        ".RRRRRRRR.",
        "...WWWW...",
        "...WWWW...",
        "....WW....",
    ],
    [
        "..........",
        "..RRRRRR..",
        ".RRRRRRRR.",
        "RRWRRRRWRR",
        "RRRRRRRRRR",
        ".RRRRRRRR.",
        "...WWWW...",
        "...WWWW...",
        "....WW....",
    ],
    {".": None, "R": _RED, "W": _WHITE},
)

# Watermelon slice — extra black seed in the flesh.
_WATERMELON = (
    [
        "..........",
        "GGGGGGGGGG",
        "RRRRRRRRRR",
        "RRBRRRRBRR",
        "RRRRRRRRRR",
        ".RRRRRRRR.",
        "..RRRRRR..",
        "...RRRR...",
        "....RR....",
    ],
    [
        "..........",
        "GGGGGGGGGG",
        "RRRRRRRRRR",
        "RRBRRRRBRR",
        "RRRRBRRRRR",
        ".RRRRRRRR.",
        "..RRRRRR..",
        "...RRRR...",
        "....RR....",
    ],
    {".": None, "G": _LEAF_G, "R": _RED, "B": _BLACK},
)

# Umbrella — one half of the canopy is the wrong shade of blue.
_UMBRELLA = (
    [
        "....B.....",
        "...BBB....",
        "..BBBBB...",
        ".BBBBBBBB.",
        "BBBBBBBBBB",
        "....H.....",
        "....H.....",
        "....H.....",
        "....HH....",
    ],
    [
        "....B.....",
        "...BBV....",
        "..BBVVV...",
        ".BBBVVVVV.",
        "BBBBVVVVVV",
        "....H.....",
        "....H.....",
        "....H.....",
        "....HH....",
    ],
    {".": None, "B": _BLUE, "V": _CYAN, "H": _BROWN},
)

# Cactus — the right-side arm is missing.
_CACTUS = (
    [
        "....G.....",
        "....G.....",
        "....G.....",
        "G...G...G.",
        "GG..G..GG.",
        ".GGGGGGG..",
        "....G.....",
        "....G.....",
        "...PPP....",
    ],
    [
        "....G.....",
        "....G.....",
        "....G.....",
        "G...G.....",
        "GG..G.....",
        ".GGGGG....",
        "....G.....",
        "....G.....",
        "...PPP....",
    ],
    {".": None, "G": _LEAF_G, "P": _BROWN},
)

# Candle — flame tilted one column right of the wick.
_CANDLE = (
    [
        "....Y.....",
        "...YYY....",
        "...YOY....",
        "....K.....",
        ".WWWWWWWW.",
        ".WWWWWWWW.",
        ".WWWWWWWW.",
        ".WWWWWWWW.",
        ".WWWWWWWW.",
    ],
    [
        ".....Y....",
        "....YYY...",
        "....YOY...",
        "....K.....",
        ".WWWWWWWW.",
        ".WWWWWWWW.",
        ".WWWWWWWW.",
        ".WWWWWWWW.",
        ".WWWWWWWW.",
    ],
    {".": None, "Y": _YELLOW, "O": _ORANGE, "W": _CREAM, "K": _BLACK},
)

# Eye — pupil shifted one column to the side.
_EYE = (
    [
        "..........",
        ".WWWWWWWW.",
        "WWWWWWWWWW",
        "WWWBBBWWWW",
        "WWWBBBWWWW",
        "WWWBBBWWWW",
        "WWWWWWWWWW",
        ".WWWWWWWW.",
        "..........",
    ],
    [
        "..........",
        ".WWWWWWWW.",
        "WWWWWWWWWW",
        "WWWWBBBWWW",
        "WWWWBBBWWW",
        "WWWWBBBWWW",
        "WWWWWWWWWW",
        ".WWWWWWWW.",
        "..........",
    ],
    {".": None, "W": _WHITE, "B": _BLACK},
)

# Dice — center pip added to the four corner pips.
_DICE = (
    [
        ".WWWWWWWW.",
        "WBWWWWWWBW",
        "WWWWWWWWWW",
        "WWWWWWWWWW",
        "WWWWWWWWWW",
        "WWWWWWWWWW",
        "WWWWWWWWWW",
        "WBWWWWWWBW",
        ".WWWWWWWW.",
    ],
    [
        ".WWWWWWWW.",
        "WBWWWWWWBW",
        "WWWWWWWWWW",
        "WWWWWWWWWW",
        "WWWWBWWWWW",
        "WWWWWWWWWW",
        "WWWWWWWWWW",
        "WBWWWWWWBW",
        ".WWWWWWWW.",
    ],
    {".": None, "W": _WHITE, "B": _BLACK},
)

_PUZZLES = (
    _SMILE, _HEART, _APPLE, _FISH, _STAR, _MUSHROOM,
    _WATERMELON, _UMBRELLA, _CACTUS, _CANDLE, _EYE, _DICE,
)


# === Chrome / HUD ========================================================

def _draw_chrome():
    _LCD.fillScreen(_BLACK)
    _LCD.fillRect(0, 0, _W, 20, _DARK)
    _LCD.fillRect(0, 20, _W, 1, _ORANGE)
    _LCD.setTextSize(1)
    _LCD.setTextColor(_ORANGE, _DARK)
    _LCD.drawString("Spot the Odd One", 6, 5)
    _LCD.fillRect(0, _H - 18, _W, 18, _DARK)
    _LCD.setTextColor(_GRAY_MID, _DARK)
    hint = ",.;/ move  SPACE pick  ` exit"
    _LCD.drawString(hint, (_W - _LCD.textWidth(hint)) // 2, _H - 14)


def _update_header(score, lives):
    # Right portion only — repainting the whole header every tick
    # would flicker the title text.
    _LCD.fillRect(140, 0, _W - 140, 20, _DARK)
    _LCD.setTextSize(1)
    _LCD.setTextColor(_CREAM, _DARK)
    text = "score {}  lives {}".format(score, lives)
    x = _W - 6 - _LCD.textWidth(text)
    _LCD.drawString(text, x, 5)


# === Grid + cursor =======================================================

def _draw_cursor(idx, on):
    """Paint or erase the 1-px cell highlight. Cells are contiguous,
    so erasing with black plays nice with neighboring borders and
    doesn't bleed into the centered icon (~20 px horizontal margin
    on each side of the 60-wide cell)."""
    x, y = _cell_xy(idx)
    color = _ORANGE if on else _BLACK
    _LCD.fillRect(x, y, _CELL_W, 1, color)
    _LCD.fillRect(x, y + _CELL_H - 1, _CELL_W, 1, color)
    _LCD.fillRect(x, y, 1, _CELL_H, color)
    _LCD.fillRect(x + _CELL_W - 1, y, 1, _CELL_H, color)


def _draw_grid(puzzle, diff_idx, invert):
    normal, different, palette = puzzle
    bm_default = different if invert else normal
    bm_odd = normal if invert else different
    # Clear the body band (header + hairline above stay untouched).
    _LCD.fillRect(0, 21, _W, _H - 21 - 18, _BLACK)
    for i in range(16):
        cx, cy = _cell_center(i)
        bm = bm_odd if i == diff_idx else bm_default
        _draw_bitmap(cx, cy, bm, palette)


def _flash_cell(idx, color, ms):
    x, y = _cell_xy(idx)
    _LCD.fillRect(x, y, _CELL_W, _CELL_H, color)
    time.sleep_ms(ms)


def _restore_cell(idx, puzzle, diff_idx, invert):
    """Repaint a single cell from scratch — used after the red flash
    so the picked cell returns to its icon and the round can
    continue."""
    x, y = _cell_xy(idx)
    _LCD.fillRect(x, y, _CELL_W, _CELL_H, _BLACK)
    cx, cy = _cell_center(idx)
    normal, different, palette = puzzle
    bm_default = different if invert else normal
    bm_odd = normal if invert else different
    bm = bm_odd if idx == diff_idx else bm_default
    _draw_bitmap(cx, cy, bm, palette)


# === Input ===============================================================

def _key_intent(k):
    if k is None:
        return None
    if isinstance(k, int):
        if k in (0x1B, 0x08, 0x09, 0x7F, 0x03):
            return ("exit",)
        if k == 0x20:
            return ("pick",)
        if k in (0x0A, 0x0D):
            return ("pick",)
        if 0x20 < k <= 0x7E:
            k = chr(k)
        else:
            return None
    if not isinstance(k, str) or not k:
        return None
    ch = k.lower()
    if ch == " ":
        return ("pick",)
    if ch in ("`", "~"):
        return ("exit",)
    if ch in (",", "a"):
        return ("left",)
    if ch in ("/", "d"):
        return ("right",)
    if ch in (";", "w"):
        return ("up",)
    if ch in (".", "s"):
        return ("down",)
    if ch == "r":
        return ("restart",)
    return None


def _move_cursor(cur, intent):
    r = cur // 4
    c = cur % 4
    if intent == "left":
        c = (c - 1) % 4
    elif intent == "right":
        c = (c + 1) % 4
    elif intent == "up":
        r = (r - 1) % 4
    elif intent == "down":
        r = (r + 1) % 4
    return r * 4 + c


# === Game flow ===========================================================

def _play_puzzle(kb, score, lives):
    """One puzzle. Returns (score, lives, exited_early)."""
    puzzle = random.choice(_PUZZLES)
    diff_idx = random.randint(0, 15)
    invert = random.randint(0, 1)
    # Random starting cursor: occasionally lands on the answer for a
    # freebie, which feels lucky rather than buggy.
    cursor = random.randint(0, 15)

    _draw_grid(puzzle, diff_idx, invert)
    _draw_cursor(cursor, True)
    _update_header(score, lives)

    while True:
        kb.tick()
        intent = _key_intent(kb.get_key())
        if intent is not None:
            tag = intent[0]
            if tag == "exit":
                return score, lives, True
            if tag in ("left", "right", "up", "down"):
                _draw_cursor(cursor, False)
                cursor = _move_cursor(cursor, tag)
                _draw_cursor(cursor, True)
            elif tag == "pick":
                if cursor == diff_idx:
                    _flash_cell(cursor, _GREEN, _FLASH_MS)
                    return score + 1, lives, False
                _flash_cell(cursor, _RED, _FLASH_MS)
                lives -= 1
                _restore_cell(cursor, puzzle, diff_idx, invert)
                _draw_cursor(cursor, True)
                _update_header(score, lives)
                if lives <= 0:
                    return score, lives, False
        time.sleep_ms(40)


def _game_over(kb, score):
    """Blocking end-of-game screen. Returns 'restart' or 'exit'."""
    _LCD.fillRect(0, 21, _W, _H - 21 - 18, _BLACK)
    _LCD.setTextSize(2)
    _LCD.setTextColor(_ORANGE, _BLACK)
    t = "Game Over"
    _LCD.drawString(t, (_W - _LCD.textWidth(t)) // 2, 34)
    _LCD.setTextSize(1)
    _LCD.setTextColor(_CREAM, _BLACK)
    s = "score: {}".format(score)
    _LCD.drawString(s, (_W - _LCD.textWidth(s)) // 2, 68)
    _LCD.setTextColor(_GRAY_MID, _BLACK)
    h = "R again   ` exit"
    _LCD.drawString(h, (_W - _LCD.textWidth(h)) // 2, 92)

    while True:
        kb.tick()
        i = _key_intent(kb.get_key())
        if i is not None:
            if i[0] == "restart":
                return "restart"
            if i[0] == "exit":
                return "exit"
        time.sleep_ms(40)


def run():
    _set_font()
    kb = MatrixKeyboard()
    # Debounce the launcher keypress so it doesn't immediately pick
    # the random starting cell. Same 400 ms window the other apps use.
    time.sleep_ms(400)
    try:
        while True:
            score = 0
            lives = _START_LIVES
            _draw_chrome()
            while lives > 0:
                score, lives, exited = _play_puzzle(kb, score, lives)
                if exited:
                    return
            if _game_over(kb, score) == "exit":
                return
    finally:
        # Mirror snake / whack / claude_buddy: clear, brief pause,
        # soft-reset back to the launcher. UIFlow 2.0 has no
        # return-to-launcher API.
        try:
            _LCD.fillScreen(_BLACK)
        except Exception as e:
            print("spot_diff: clear warning:", e)
        time.sleep_ms(200)
        machine.reset()


# UIFlow's App List invokes apps both as __main__ and via import; the
# empirical behavior is always-run, so just call run() bare (same
# pattern as snake / whack / hello).
run()
